apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-vegjtrmr
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-vegjtrmr:86f0711bd5068ca4890899f125c0572492a29945@sha256:89e703985277f749141fdb3897a8bf19a3fd5bbbbdb5161f458658f182824241
          name: container-image
